version: "3.3"
services:

  redisgraph:
    container_name: redisgraph
    image: redislabs/redisgraph:latest  
    ports:
      - "6379:6379"

  redisinsight:
    container_name: redis-client
    image: redislabs/redisinsight:latest
    ports:
      - "81:8001"

  neo4j:
    container_name: neo4j
    image: neo4j:latest
    ports: 
      - "82:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/neo4jpassword
      NEO4J_apoc_export_file_enabled: 'true'
      NEO4J_apoc_import_file_enabled: 'true'
      NEO4J_apoc_import_file_use__neo4j__config: 'true'
      NEO4J_PLUGINS:  '["apoc"]'

  apache-age:
    container_name: apache-age
    image: apache/age:latest
    ports: 
      - "5455:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: apache-age

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "83:80"